"""empty message

Revision ID: a16d81b52430
Revises:
Create Date: 2025-11-04 20:27:22.028893

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "a16d81b52430"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "negotiations",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("item_id", sa.Integer(), nullable=False),
        sa.Column("seller_id", sa.Integer(), nullable=False),
        sa.Column("buyer_id", sa.Integer(), nullable=False),
        sa.Column("total_currency", sa.String(length=3), nullable=True),
        sa.Column("total_amount", sa.Numeric(), nullable=True),
        sa.Column("started_by_user_id", sa.Integer(), nullable=False),
        sa.Column(
            "status",
            sa.Enum("PENDING", "ACCEPTED", "BROKEN_OFF", name="status"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("negotiations")
    # ### end Alembic commands ###
