services:
  shell:
    image: micro-usf
    build:
      context: .
      dockerfile: docker/Dockerfile

  postgresdb:
    image: postgres:15.3
    volumes:
      - ./docker/postgres_initdb:/docker-entrypoint-initdb.d
    environment:
      - POSTGRES_PASSWORD=usf
      - POSTGRES_USER=usf
    ports:
      - "5432:5432"

  redis:
    image: redis:6
    ports:
      - "6379:6379"

  rabbitmq:
    image: rabbitmq:3.11.2-management
    ports:
      - "5672:5672"
      - "15672:15672"

  zipkin:
    image: openzipkin/zipkin:2.23.19
    ports:
      - "9411:9411"

  prometheus:
    image: bitnami/prometheus:2.44.0
    ports:
      - "9090:9090"
        
  grafana:
    image: grafana/grafana:9.5.2
    ports:
      - "3000:3000"

  mongodb:
    image: mongo:6.0.5
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: usf
      MONGO_INITDB_ROOT_PASSWORD: usf

  mongo-express:
    image: mongo-express:1.0.0-alpha.4
    depends_on:
      - mongodb
    restart: unless-stopped
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: usf
      ME_CONFIG_MONGODB_ADMINPASSWORD: usf
      ME_CONFIG_MONGODB_URL: mongodb://usf:usf@mongodb:27017/

  items:
    image: micro-usf
    hostname: docker-usf-items
    ports:
      - "8100:8100"
    volumes:
      - ./used_stuff_market/items:/usr/src/app
      - ./used_stuff_market/libraries:/usr/src/libraries
    environment:
      PYTHONPATH: /usr/src/libraries:/usr/src/app
    command: bash -c 'alembic upgrade head && uvicorn items.api:app --host 0.0.0.0 --port 8100 --reload'

  negotiations:
    image: micro-usf
    hostname: docker-usf-negotiations
    ports:
      - "8200:8200"
    volumes:
      - ./used_stuff_market/negotiations:/usr/src/app
      - ./used_stuff_market/libraries:/usr/src/libraries
    environment:
      PYTHONPATH: /usr/src/libraries:/usr/src/app
    command: bash -c 'python negotiations/migrations.py && uvicorn negotiations.api:app --host 0.0.0.0 --port 8200 --reload'

  availability:
    image: micro-usf
    hostname: docker-usf-availability
    ports:
      - "8300:8300"
    volumes:
      - ./used_stuff_market/availability:/usr/src/app
      - ./used_stuff_market/libraries:/usr/src/libraries
    environment:
      PYTHONPATH: /usr/src/libraries:/usr/src/app
    command: bash -c 'alembic upgrade head && uvicorn availability.api:app --host 0.0.0.0 --port 8300 --reload'

  availability-consumer:
    image: micro-usf
    hostname: docker-usf-availability-consumer
    volumes:
      - ./used_stuff_market/availability:/usr/src/app
      - ./used_stuff_market/libraries:/usr/src/libraries
    environment:
      PYTHONPATH: /usr/src/libraries:/usr/src/app
    command: watchfiles "python availability/consumer.py" /usr/src/app

  orchestrator:
    image: micro-usf
    hostname: docker-usf-orchestrator
    volumes:
      - ./used_stuff_market/orchestrator:/usr/src/app
      - ./used_stuff_market/libraries:/usr/src/libraries
    environment:
      PYTHONPATH: /usr/src/libraries:/usr/src/app
    command: bash -c 'python orchestrator/migrations.py && watchfiles "python orchestrator/consumer.py" /usr/src/app'

  catalog:
    image: micro-usf
    hostname: docker-usf-catalog
    ports:
      - "8400:8400"
    volumes:
      - ./used_stuff_market/catalog:/usr/src/app
      - ./used_stuff_market/libraries:/usr/src/libraries
    environment:
      PYTHONPATH: /usr/src/libraries:/usr/src/app
    command: bash -c 'python catalog/migrations.py && uvicorn catalog.api:app --host 0.0.0.0 --port 8400 --reload'

  catalog-consumer:
    image: micro-usf
    hostname: docker-usf-catalog-consumer
    volumes:
      - ./used_stuff_market/catalog:/usr/src/app
      - ./used_stuff_market/libraries:/usr/src/libraries
    environment:
      PYTHONPATH: /usr/src/libraries:/usr/src/app
    command: watchfiles "python catalog/consumer.py" /usr/src/app

  likes:
    image: micro-usf
    hostname: docker-usf-likes
    ports:
      - "8500:8500"
    volumes:
      - ./used_stuff_market/likes:/usr/src/app
      - ./used_stuff_market/libraries:/usr/src/libraries
    environment:
      PYTHONPATH: /usr/src/libraries:/usr/src/app
    command: bash -c 'alembic upgrade head && uvicorn likes.api:app --host 0.0.0.0 --port 8500 --reload'