"""empty message

Revision ID: 5951600c8815
Revises: d7b53a51355f
Create Date: 2025-11-04 21:16:16.245318

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '5951600c8815'
down_revision = 'd7b53a51355f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('outbox_entries', sa.Column('headers', postgresql.JSONB(astext_type=sa.Text()), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('outbox_entries', 'headers')
    # ### end Alembic commands ###
