"""Add Likes

Revision ID: 878ada3274a2
Revises:
Create Date: 2022-12-04 22:23:48.529880

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "878ada3274a2"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "likes",
        sa.Column("item_id", sa.Integer(), nullable=False),
        sa.Column("liker", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("item_id", "liker"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("likes")
    # ### end Alembic commands ###
