"""starting_price_* columns to price_*

Revision ID: 4768b1327078
Revises: e7ea5d20a590
Create Date: 2022-11-30 21:45:40.298405

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "4768b1327078"
down_revision = "e7ea5d20a590"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("items", sa.Column("price_amount", sa.Numeric(), nullable=False))
    op.add_column(
        "items", sa.Column("price_currency", sa.String(length=3), nullable=False)
    )
    op.drop_column("items", "starting_price_amount")
    op.drop_column("items", "starting_price_currency")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "items",
        sa.Column(
            "starting_price_currency",
            sa.VARCHAR(length=3),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.add_column(
        "items",
        sa.Column(
            "starting_price_amount", sa.NUMERIC(), autoincrement=False, nullable=False
        ),
    )
    op.drop_column("items", "price_currency")
    op.drop_column("items", "price_amount")
    # ### end Alembic commands ###
