"""Add Outbox Entries

Revision ID: c2fc1d28f2fe
Revises: 4768b1327078
Create Date: 2022-12-05 22:55:45.389762

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "c2fc1d28f2fe"
down_revision = "4768b1327078"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "outbox_entries",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("queue", sa.String(length=255), nullable=False),
        sa.Column("data", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("retries_left", sa.Integer(), nullable=False),
        sa.Column(
            "when_created",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("outbox_entries")
    # ### end Alembic commands ###
