"""Add version_id

Revision ID: e7ea5d20a590
Revises: 6c54457ba095
Create Date: 2022-11-30 21:34:00.010085

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "e7ea5d20a590"
down_revision = "6c54457ba095"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("items", sa.Column("version_id", sa.Integer(), nullable=False))
    op.alter_column("items", "owner_id", existing_type=sa.INTEGER(), nullable=False)
    op.alter_column("items", "title", existing_type=sa.VARCHAR(), nullable=False)
    op.alter_column("items", "description", existing_type=sa.VARCHAR(), nullable=False)
    op.alter_column(
        "items", "starting_price_amount", existing_type=sa.NUMERIC(), nullable=False
    )
    op.alter_column(
        "items",
        "starting_price_currency",
        existing_type=sa.VARCHAR(length=3),
        nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "items",
        "starting_price_currency",
        existing_type=sa.VARCHAR(length=3),
        nullable=True,
    )
    op.alter_column(
        "items", "starting_price_amount", existing_type=sa.NUMERIC(), nullable=True
    )
    op.alter_column("items", "description", existing_type=sa.VARCHAR(), nullable=True)
    op.alter_column("items", "title", existing_type=sa.VARCHAR(), nullable=True)
    op.alter_column("items", "owner_id", existing_type=sa.INTEGER(), nullable=True)
    op.drop_column("items", "version_id")
    # ### end Alembic commands ###
